import os,sys,time
os.system("clear")
def hanasakam():
         print("██▓███   ▒█████   ██▓     ██▓    ▄▄▄      ")
         print("▓██░  ██▒▒██▒  ██▒▓██▒    ▓██▒   ▒████▄    ")
         print("▓██░ ██▓▒▒██░  ██▒▒██░    ▒██░   ▒██  ▀█▄  ")
         print("▒██▄█▓▒ ▒▒██   ██░▒██░    ▒██░   ░██▄▄▄▄██ ")
         print("▒██▒ ░  ░░ ████▓▒░░██████▒░██████▒▓█   ▓██▒")
         print("▒▓▒░ ░  ░░ ▒░▒░▒░ ░ ▒░▓  ░░ ▒░▓  ░▒▒   ▓▒█░")
         print("░▒ ░       ░ ▒ ▒░ ░ ░ ▒  ░░ ░ ▒  ░ ▒   ▒▒ ░")
         print("░░       ░ ░ ░ ▒    ░ ░     ░ ░    ░   ▒   ")
         print("             ░ ░      ░  ░    ░  ░     ░  ░")
         print("========================================")
         print("My Github : https://github.com/hamayassad")
         print("My Telgram : hama_mnalxor")
         print("My Chanall : termuxviptools")
         print("========================================")
hanasakam()
time.sleep(10)
def hanasakam():
	print("[✓]installing... :) ")
hanasakam()
time.sleep(15)
os.system("termux-setup-storage")
time.sleep(5)
os.system("pkg install figlet -y")
os.system("clear")
os.system("pkg install wget -y")
os.system("clear")
os.system("pip install argparse")
os.system("clear")
os.system("pip install marshal")
os.system("clear")
os.system("pip install scapy")
os.system("clear")
os.system("pkg install python2")
os.system("clear")
os.system("pip install requests")
os.system("clear")
os.system("pip install phonenumbers")
os.system("clear")
os.system("pkg install figlet -y")
os.system("clear")
os.system("pkg install mpv -y")
os.system("clear")
os.system("pip install wget")
os.system("clear")
os.system("pkg update -y &&pkg upgrade -y")
os.system("clear")
os.system("apt update -y")
os.system("clear")
os.system("pip install tools")
os.system("clear")
os.system("apt upgrade -y")
os.system("clear")
os.system("pkg Install nmap -y")
os.system("clear")
os.system("pkg install SETAN -y")
os.system("clear")
os.system("pkg install nodejs -y")
os.system("clear")
os.system("pip install requests")
os.system("clear")
os.system("pip2 install requests")
os.system("clear")
os.system("pip2 install mechanize")
os.system("clear")
os.system("pip install telethon")
os.system("clear")
os.system("pip inatall phonenumbers")
os.system("clear")
os.system("pkg install o-editor -y")
os.system("clear")
os.system("apt install dnsutils -y")
os.system("clear")
os.system("apt Install Nmap -y")
os.system("clear")
os.system("apt update -y")
os.system("clear")
os.system("apt upgrade -y")
os.system("clear")
os.system("pkg intsall nano -y")
os.system("clear")
os.system("pkg install openssl-tool -y")
os.system("clear")
os.system("pkg install curl -y")
os.system("clear")
os.system("pkg install figlet -y")
os.system("clear")
os.system("pkg install unzip -y")
os.system("clear")
os.system("pkg install zip -y")
os.system("clear")
os.system("pkg install sl -y")
os.system("clear")
os.system("pkg install tor -y")
os.system("clear")
os.system("pkg install php -y")
os.system("clear")
os.system("pkg install fish -y")
os.system("clear")
def hanasakam():
         print("██▓███   ▒█████   ██▓     ██▓    ▄▄▄      ")
         print("▓██░  ██▒▒██▒  ██▒▓██▒    ▓██▒   ▒████▄    ")
         print("▓██░ ██▓▒▒██░  ██▒▒██░    ▒██░   ▒██  ▀█▄  ")
         print("▒██▄█▓▒ ▒▒██   ██░▒██░    ▒██░   ░██▄▄▄▄██ ")
         print("▒██▒ ░  ░░ ████▓▒░░██████▒░██████▒▓█   ▓██▒")
         print("▒▓▒░ ░  ░░ ▒░▒░▒░ ░ ▒░▓  ░░ ▒░▓  ░▒▒   ▓▒█░")
         print("░▒ ░       ░ ▒ ▒░ ░ ░ ▒  ░░ ░ ▒  ░ ▒   ▒▒ ░")
         print("░░       ░ ░ ░ ▒    ░ ░     ░ ░    ░   ▒   ")
         print("             ░ ░      ░  ░    ░  ░     ░  ░")
         print("===========================================")
os.system("fish")
os.system("clear")
